version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  # Python dependencies (Manager)
  - package-ecosystem: "uv"
    directory: "/manager"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  # Python dependencies (Runner)
  - package-ecosystem: "uv"
    directory: "/runner"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
